"""Does the calibration solver still claim accuracy it has not measured?

Three properties matter, and each one failed before:

  four points cannot be validated
      They determine an 8-DOF homography exactly, so the fit passes through
      every one and the error is zero by construction. That zero was being
      reported as held_out_error_m and stored against every camera as
      0.017 m, which is where "validated to 1.7 cm" came from.

  a held-out point must be predicted, not fitted
      With 5+ points the solver refits without each point and predicts it.
      Feeding it deliberately wrong world coordinates must produce a large
      error; if it does not, the point is being fitted rather than held out.

  the quality gate must reject bad calibrations
      A gate that says "good" whatever the error is decoration.

Run:  python -m backend.scripts.test_calibration_honesty
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from backend.services.auto_calibrator import HomographyEngine       # noqa: E402

FRAME = (1920, 1080)

# Correspondences generated by projecting ground points through a real
# pinhole geometry, rather than by drawing a trapezoid by hand. Hand-drawn
# points put the projective horizon inside the frame, which the solver
# correctly refuses — a road whose vanishing line crosses the visible image
# would divide by zero.
#
# Camera 8 m up, 1400 px focal length, horizon 150 px above the top edge:
#     v = vp_y + f*h/Y        u = vp_x + f*X/Y
VP_X, VP_Y, FOCAL, HEIGHT = 960.0, -150.0, 1400.0, 8.0


def project(X: float, Y: float) -> tuple:
    return (VP_X + FOCAL * X / Y, VP_Y + FOCAL * HEIGHT / Y)


WORLD = [(-6.0, 12.0), (6.0, 12.0), (6.0, 30.0), (-6.0, 30.0),
         (0.0, 20.0), (-3.5, 16.0)]
IMG = [project(*w) for w in WORLD]


def show(name, r):
    print(f"\n{name}")
    print(f"   valid          {r.is_valid}")
    print(f"   quality_gate   {r.quality_gate}")
    print(f"   held_out_m     {r.held_out_error_m}")
    print(f"   loo_rms_m      {round(r.loo_rms_error_m, 4)}")
    print(f"   message        {r.message}")


fails = []

# 1. Four points: exact fit, nothing to validate against.
r4 = HomographyEngine.solve_homography(IMG[:4], WORLD[:4], held_out_idx=0,
                                       frame_size=FRAME)
show("4 points (exactly determined)", r4)
if r4.held_out_error_m is not None:
    fails.append("4 points reported a held-out error, which cannot exist")
if r4.quality_gate == "good":
    fails.append("4 points were graded 'good' without any validation")

# 2. Six good points: held-out prediction should be small.
r6 = HomographyEngine.solve_homography(IMG, WORLD, held_out_idx=4,
                                       frame_size=FRAME)
show("6 points, consistent", r6)
if r6.held_out_error_m is None:
    fails.append("6 points produced no held-out error")
elif r6.held_out_error_m > 1.0:
    fails.append(f"consistent points gave a {r6.held_out_error_m:.2f} m "
                 f"held-out error, which suggests the solve is wrong")

# 3. One point given deliberately wrong ground coordinates, 10 m out. If it is
#    genuinely held out, the error must show it.
bad = list(WORLD)
bad[4] = (0.0, 30.0)                      # was (0, 20): moved 10 m downrange
rb = HomographyEngine.solve_homography(IMG, bad, held_out_idx=4,
                                       frame_size=FRAME)
show("6 points, one moved 10 m", rb)
if rb.held_out_error_m is None or rb.held_out_error_m < 2.0:
    fails.append(f"a point moved 10 m produced held-out error "
                 f"{rb.held_out_error_m} — it is being fitted, not held out")
if rb.quality_gate == "good":
    fails.append("a 10 m error was still graded 'good'")

# 4. Collinear points: must be refused, not fitted.
rc = HomographyEngine.solve_homography(
    [(100, 500), (400, 500), (700, 500), (1000, 500), (1300, 500)],
    [(0, 10), (3, 10), (6, 10), (9, 10), (12, 10)], held_out_idx=2,
    frame_size=FRAME)
show("5 collinear points (degenerate)", rc)
if rc.is_valid:
    fails.append("collinear points were accepted as a valid homography")

print("\n" + "=" * 58)
if fails:
    print(f"{len(fails)} PROBLEM(S):")
    for f in fails:
        print(f"   - {f}")
    sys.exit(1)
print("All four properties hold: the solver reports only what it measured.")
