"""Audit log search filters actually filter, and non-admins are refused."""
from __future__ import annotations

import pytest
from fastapi.testclient import TestClient

from backend.main import app

client = TestClient(app)


@pytest.fixture(autouse=True)
def _real_auth(clear_get_current_user_override):
    """This file's whole point is checking a REAL user's role is enforced —
    see conftest.py for why that needs the global override cleared first."""
    yield

# Cached — see test_camera_bulk_onboarding.py for why: uncached logins across
# the new test files added up to more than the 10/minute limit and starved
# test_department_scoping.py's own logins with unrelated 429s.
_TOKENS: dict[str, str] = {}


def _login(username: str, password: str) -> dict:
    if username not in _TOKENS:
        r = client.post("/api/v1/auth/login",
                        json={"username": username, "password": password})
        assert r.status_code == 200, r.text
        _TOKENS[username] = r.json()["access_token"]
    return {"Authorization": f"Bearer {_TOKENS[username]}"}


def test_action_filter_returns_only_that_action():
    h = _login("admin", "admin123")
    # LOGIN rows exist from every test in this suite logging in.
    r = client.get("/api/v1/audit-log", params={"action": "LOGIN", "limit": 50},
                   headers=h)
    assert r.status_code == 200, r.text
    rows = r.json()
    assert rows, "expected at least one LOGIN row after this test's own login"
    assert all(row["action"] == "LOGIN" for row in rows)


def test_bad_date_is_a_400_not_a_500():
    h = _login("admin", "admin123")
    r = client.get("/api/v1/audit-log", params={"date_from": "not-a-date"},
                   headers=h)
    assert r.status_code == 400


def test_non_admin_is_refused():
    h = _login("viewer", "viewer123")
    r = client.get("/api/v1/audit-log", headers=h)
    assert r.status_code == 403


def test_actions_endpoint_lists_real_values_not_a_guess():
    h = _login("admin", "admin123")
    r = client.get("/api/v1/audit-log/actions", headers=h)
    assert r.status_code == 200, r.text
    body = r.json()
    assert "LOGIN" in body["actions"], (
        "the distinct-actions list should include LOGIN, which this test "
        "itself just generated by logging in")
